### ISSUE TITLE
ext-clipboard-manager doesn't seem to work?

### ISSUE THREAD

**Issue by colemickens** [lilyinstarlight/nixos-cosmic#408]
Hi! You asked me to file this, so I am.

I have a hard time imagining that a NixOS-ism is causing Wayland/clipboard issues, but I guess this is as good a place as any to track it.

I'd provide a screenshot but, well, cosmic-screenshot is being a bit annoying. And regardless, it would be a screenshot of an empty panel.

I've clearly copy-pasted many things since installing *and* adding it to my panel, yet it remains empty.

---

as always, massive thanks. I <3 cosmic, I <3 nixos, I <3 nixos-cosmic.

**Comment by FriederHannenheim** [comment]
What I've also found is that the wl-clipboard utilities don't work, though I just assume that the necessary protocol is not implemented in cosmic-comp

**Comment by FelixSchausberger** [comment]
Have you tried the clipboard manager for cosmic?

https://github.com/cosmic-utils/clipboard-manager

Would be super cool if it could already be integrated into cosmic-applets but I don't know what else is needed for it

**Comment by lilyinstarlight** [comment]
@FelixSchausberger Yes, that is already packaged as cosmic-ext-clipboard-manager which this issue is for, but I haven't had much laptop time but I intend to investigate and debug within a few days

**Comment by lilyinstarlight** [comment]
Hmm seems to be throwing the error `A required Wayland protocol (zwlr_data_control_manager_v1 version 1) is not supported by the compositor` 🤔

**Comment by lilyinstarlight** [comment]
Oh yeah, it looks like you're probably gonna want to set `environment.sessionVariables.COSMIC_DATA_CONTROL_ENABLED = 1` in your NixOS config for it (see <https://github.com/cosmic-utils/clipboard-manager/blob/5396b3cc0b36f9fa229302cc0c97cd39c339ef4a/README.md?plain=1#L30>)

I'll go ahead and add that to the test VM. If someone would like to add that gotcha to the readme, a PR would be appreciated! Otherwise I'll get to it soon enough :)

**Comment by lilyinstarlight** [comment]
Added to readme. Feel free to re-open if you're not satisfied with this :)
