### ISSUE TITLE
cosmic-comp system actions are leaking Xwayland into PATH

### ISSUE THREAD

**Issue by sebastianrasor** [lilyinstarlight/nixos-cosmic#427]
I recently decided to start daily driving Cosmic on my NixOS laptop and I'm loving it, this isn't an issue with Cosmic.

What I am confused by is why all of my terminals think they're in a Nix shell (Starship's Nix module). I did some digging into Starship's Nix module code and found that it's checking if any of the PATH entries begin with /nix/store, which is usually a decent enough hack to detect `nix shell` usage.

The issue seems to be caused [here](https://github.com/lilyinstarlight/nixos-cosmic/blob/df96b920c4014334085688824a073b1799069043/pkgs/cosmic-comp/package.nix#L75). I'm not entirely sure how this all interacts, but is there any reason we can't just add the XWayland package as a dependency so it's guaranteed to be in the existing Nix PATH entries, rather than creating a new PATH entry?

**Comment by lilyinstarlight** [comment]
That likely isn't going to be the only place you have issues. I can see about alternatively injecting the XWayland PATH or suffixing, but the correct fix here is for starship to use `IN_NIX_SHELL` env var for detecting shells. As COSMIC isn't going to be the only way this happens and starship already has a much better way to be detecting something than a very faulty heuristic

**Comment by sebastianrasor** [comment]
> That likely isn't going to be the only place you have issues. I can see about alternatively injecting the XWayland PATH or suffixing, but the correct fix here is for starship to use `IN_NIX_SHELL` env var for detecting dev shells. As COSMIC isn't going to be the only way this happens and starship already has a much better way to be detecting something than a very faulty heuristic

The issue is that without the flawed heuristic, Starship cannot detect when `nix shell` is used. The `IN_NIX_SHELL` variable has not been implemented yet in Nix. I understand that Cosmic isn't the only place it's possible for this to happen, but after an extended duration using my current system with very little changes, switching to Cosmic is the first time I've encountered this false positive on the Starship heuristic.

I just wanted to bring it up as I'm not entirely sure if there's a better way, I just wanted to get the conversation started.

**Comment by lilyinstarlight** [comment]
Okay I looked further and you meant `nix shell`, which isn't related to `nix-shell` and not at all a dev shell (but it seems starship upsream has conflated the two...) and yeah `IN_NIX_SHELL` is not set for non-dev-shells

It looks like starship also does not enable this option by default since it breaks if you breathe on it wrong. I'll see if starship can do something else, and report upstream

**Comment by lilyinstarlight** [comment]
> I just wanted to bring it up as I'm not entirely sure if there's a better way, I just wanted to get the conversation started.

Yeah, no, I get that! I'm just still unsure why it makes much sense for the better way to be discussed here :)

Judging by searching through a few starship issues, it looks like most people use their own workarounds rather than the `heuristic` option, and they generally involve aliasing `nix shell`. But also starship could probably make the heuristic better by checking `SHLVL` being 2 or greater as well?

**Comment by sebastianrasor** [comment]
> > I just wanted to bring it up as I'm not entirely sure if there's a better way, I just wanted to get the conversation started.
> 
> Yeah, no, I get that! I'm just still unsure why it makes much sense for the better way to be discussed here :)
> 
> Judging by searching through a few starship issues, it looks like most people use their own workarounds rather than the `heuristic` option, and they generally involve aliasing `nix shell`. But also starship could probably make the heuristic better by checking `SHLVL` being 2 or greater as well?

The reason I opened the discussion here was just to see if there's a better way for nixos-cosmic to get the Xwayland binary into PATH vs just prepending the nix store bin directory to PATH.

>  Also can you share your PATH?

```
❯ echo $PATH
/nix/store/b0rrk0wcd19mqg3h8ycf3rzvjj0vkwsa-xwayland-24.1.3/bin /run/wrappers/bin /home/sebastian/.nix-profile/bin /nix/profile/bin /home/sebastian/.local/state/nix/profile/bin /etc/profiles/per-user/sebastian/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin
```

It looks like the reason that xwayland entry is there is because of this:
https://github.com/lilyinstarlight/nixos-cosmic/blob/df96b920c4014334085688824a073b1799069043/pkgs/cosmic-comp/package.nix#L75-L77

**Comment by lilyinstarlight** [comment]
> The reason I opened the discussion here was just to see if there's a better way for nixos-cosmic to get the Xwayland binary into PATH vs just prepending the nix store bin directory to PATH.

Modifying PATH is modifying PATH, so it'll have to be something that doesn't involve that at all. I've pushed a thing to hopefully help

*Please* though if you want this fixed (instead of papered around in one specific place it can manifest and which will be inevitably broken elsewhere in a place I don't control), ask the starship folks to use better heuristics (e.g. `SHLVL` checking) or to make a more dedicated `nix shell` module since conflating `nix-shell` and `nix shell` is very misleading and wrong (despite the unfortunately similar names). You could also go bother the CppNix folks to add an indicating environment variable to `nix shell` invocations (see <https://github.com/NixOS/nix/issues/6677>)

> It looks like the reason that xwayland entry is there is because of this:

I had Xwayland enabled and was not experiencing the issue you were describing (i.e. you were doing something I wasn't to manifest it), but I also discovered that cosmic-comp system actions (e.g. keybinds to start cosmic-term) do leak environment (see <https://github.com/pop-os/cosmic-comp/blob/2497992d319ad43f190044f7a7c5ebd0b5f04b2a/src/input/actions.rs#L1053-L1071>). I've attempted to make a temporary fix in nixos-cosmic to avoid that and will look into making a more permanent fix in cosmic-comp itself (e.g. dispatching spawning these processes to pop-launcher/cosmic-launcher)

> After reading through it a bit more, my question is why have this

Smithay expects Xwayland in PATH, putting it in `buildInputs` will do nothing to help the smithay/cosmic-comp Xwayland code find it (see <https://github.com/Smithay/smithay/blob/2cee41cdffd111a758b60d230b591367012887a7/src/xwayland/xserver.rs#L137-L189>)

---

Can you pull the latest HEAD of this flake and try now?

**Comment by sebastianrasor** [comment]
> _Please_ though if you want this fixed (instead of papered around in one specific place it can manifest and which will be inevitably broken elsewhere in a place I don't control), ask the starship folks to use better heuristics (e.g. `SHLVL` checking) or to make a more dedicated `nix shell` module since conflating `nix-shell` and `nix shell` is very misleading and wrong (despite the unfortunately similar names). You could also go bother the CppNix folks to add an indicating environment variable to `nix shell` invocations (see [NixOS/nix#6677](https://github.com/NixOS/nix/issues/6677))

I didn't open an issue in the Starship repo because as I mentioned before, this is first time I've actually experienced an issue with the flawed heuristic in all of my time using NixOS and Starship. They already know the heuristic is flawed, I don't think there's much that can be gained by me bringing it up again.

> but I also discovered that cosmic-comp system actions (e.g. keybinds to start cosmic-term) do leak environment

Oh that makes sense, I guess I was thinking about a red herring with the lines that I referenced.

> Can you pull the latest HEAD of this flake and try now?

This issue isn't occurring on the [latest git revision](https://github.com/lilyinstarlight/nixos-cosmic/commit/658e0710371871a2e8ff72a583f5133be87c4b7d).

**Comment by lilyinstarlight** [comment]
> They already know the heuristic is flawed, I don't think there's much that can be gained by me bringing it up again.

I gave concrete suggestions they could improve it with (not just a "hey it's broken"). But it's not that big of a deal (it sounds like you've been surprisingly lucky compared to all of the reports I've seen with it)

> This issue isn't occurring on the latest git revision.

Awesome, glad it's working okay for you now :)
